apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: telegram-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.CamelSourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    camel.source.kafka.topic: telegram-topic
    camel.source.url: telegram:bots
    camel.component.telegram.authorizationToken: ${file:/opt/kafka/external-configuration/telegram-credentials/telegram-credentials.properties:token}
---

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: telegram-chatbot
  labels:
    strimzi.io/cluster: my-second-connect-cluster
spec:
  class: TelegramChatBotSink.TelegramChatBotSink
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    telegram.bot.id: ${file:/opt/kafka/external-configuration/telegram-credentials/telegram-credentials.properties:token}
    telegram.chat.id: ${file:/opt/kafka/external-configuration/telegram-credentials/telegram-credentials.properties:chat_id}
    brainShop.AI.bot.id: ${file:/opt/kafka/external-configuration/brainshop-credentials/brainshop-credentials.properties:bot.id}
    brainShop.AI.key: ${file:/opt/kafka/external-configuration/brainshop-credentials/brainshop-credentials.properties:key}
    brainShop.AI.uid: ${file:/opt/kafka/external-configuration/brainshop-credentials/brainshop-credentials.properties:uid}
    brainShop.AI.API.header: ${file:/opt/kafka/external-configuration/brainshop-credentials/brainshop-credentials.properties:API.header}
    topics: telegram-topic